[package]
name = "vquery"
version = "0.1.0"
authors = ["r4v3n6101 <raven6107@gmail.com>"]
edition = "2021"

[dependencies]
tokio = { version = "1.17.0", features = ["net"] }
futures = "0.3.21"
combine = "4.6.3"

[dev-dependencies]
tokio = { version = "1.17.0", features = ["full"] }
