[package]
name = "vquery"
version = "0.14.0"
authors = ["r4v3n6101 <raven6107@gmail.com>"]
edition = "2018"

[dependencies]
thiserror = "1.0.22"
nom = "7.0.0"
nom-derive = "0.7.0"
bzip2 = "0.4.1"
crc = "3.0.0"
